### PR TITLE
Update of DELEGATION02

### PR DESCRIPTION
**Pull request by matsduf**
Clarified DELEGATION02.

### CODE REVIEW

**Comment by sandoche2k** [comment]
The objective of the test case written as of now : "Name servers must have distinct IP addresses". 

As per RFC " By administrative fiat, we require every zone to be available on at least two servers, and many zones have more redundancy than that"
. 
Hence, the idea is that there is no single point of failure such as the example below

ex:1: example.com has two NS ns1.example.com and ns2.example.com and if they resolve to the same IP as below :
ns1.example.com IN A 1.1.1.1
ns2.example.com IN A 1.1.1.1

Method4 and method5 calls method2 and method3 
Method2 and method3 gets the nameservers "ns1.example.com" and "ns2.example.com" and they record unique nameservers (i.e. "ns1.example.com" and "ns2.example.com")
In Method4 and method5 we obtain the unique IP address of the nameservers (i.e. 1.1.1.1)

Step2 : If the number of IP addresses obtained is less than two, this test case fails with an error

**Comment by matsduf** [comment]
@sandoche2k, yes it is true that Method4 calls Method2, but Method4 only returns the IP addresses from glue. To get the nameserver names from delegation you have to call Method2. Method5 calls Method3, but Method5 only returns the IP address in the zone, not the nameserver names.

To get all IP addresses to the nameservers you need the nameserver names to be able to query for the nameserver names thaar or out-of-zone.

**Comment by sandoche2k** [comment]
@matsduf the objective is not to have single point of failure.

I think the test should pass in the case of example below:

ns1.example.com IN A 1.1.1.1
ns2.example.com IN A 1.1.1.1
ns2.example.com IN A 1.1.1.2

**Comment by matsduf** [comment]
We have example.com delegated:
```
example.com. NS ns1.exampel.se.
example.com. NS ns2.exampel.se.
```
Neither Method4 nor Method5 will return any IP address because they are out-of-zone. You need Method2 and Method3 to get the names so that you can query for the IP addresses on public Internet.

**Comment by sandoche2k** [comment]
Yes, that is why method4 calls method2 and method5 calls method3. Isn't it?

**Comment by matsduf** [comment]
The headline is "Name servers must have distinct IP addresses" and the objective says

`If the domain have several different name server names used, they can all be using the same IP address. This may be due to a configuration error, or a workaround to a certain policy restriction. This test case checks that the name servers used does not resolve to reuse the same IP addresses.
`

**Comment by matsduf** [comment]
> Yes, that is why method4 calls method2 and method5 calls method3. Isn't it?

No. Method4 and Method5 will not query public Internet.

**Comment by sandoche2k** [comment]
And it refers to Section 4.1 of RFC 1034 says at least to name servers must be used for a delegation.

Which mentions this 
`
A given zone will be available from several name servers to insure its
availability in spite of host or communication link failure.  By
administrative fiat, we require every zone to be available on at least
two servers, and many zones have more redundancy than that.
`

**Comment by matsduf** [comment]
Method 4: Obtain "glue address records" from parent

This method tries to obtain any glue address records from the delegation in the parent zone.

(...)

Method 5: Obtain the name server address records from child

This method tries to obtain the IP addresses for the name servers used in the child zone.

**Comment by matsduf** [comment]
> And it refers to Section 4.1 of RFC 1034 says at least to name servers must be used for a delegation.

Yes, we keep that, even though it makes the Test Case less distinct. It would fit better in DELEGATION01, which we could rewrite.

**Comment by sandoche2k** [comment]
> We have example.com delegated:
```
example.com. NS ns1.exampel.se.
example.com. NS ns2.exampel.se.
```
Neither Method4 nor Method5 will return any IP address because they are out-of-zone. You need Method2 and Method3 to get the names so that you can query for the IP addresses on public Internet.

From delegation01, which calls method2 and method3 we have the following NS for example.com (from the parent and the child):
```
ns1.exampel.se.
ns2.exampel.se.
```
Step 1 in method2 says "Query the servers in Method 2 for A and AAAA addresses."
```
dig ns1.example.se -t A 
```
Will provide you the IP address for ns1.example.se. Isn't it ?

**Pull request closed without merging**
